export const MODIFY_PERSONAL_DATA = 'MODIFY_PERSONAL_DATA';
export const VIEW_DNI_TITULAR = 'VIEW_DNI_TITULAR';
export const MODIFY_CONTACT_DATA = 'MODIFY_CONTACT_DATA';
export const MODIFY_OTHER_CONTACT_DATA = 'MODIFY_OTHER_CONTACT_DATA';
export const PRESCRIBER_DETAILS = 'PRESCRIBER_DETAILS';