export const subjects = [
  '',
  'Rescate',
  'Amortización',
  'Consulta',
  'Info general',
  'Cuando recibiré mi dinero',
  'Contraseña Área Cliente',
  'Impagos',
  'Acreditia gestiones',
  'Documentación Recibida',
  'Nuevo préstamo Solicitud',
  'Reclamación',
  'LOPD',
  'Cambio de IBAN',
  'Cambios Datos personales',
  'Rescate solicitud Dni',
  'Rescate solicitud justificante iban',
  'Rescate envío de contrato',
  'Préstamo on line',
  'Contrato doble firma',
  'Desistimiento',
].map(i => ({value: i, text: i}));

export const directionTypes = [
  {value: 'I', text: 'Inbound'},
  {value: 'O', text: 'Outbound'},
];

export const inbound = [
  '',
  'Amortización',
  'Desarrollo Riesgo',
  'Consulta',
  'Registro',
  'Info general',
  'Cuando recibiré mi dinero',
  'Contraseña Área Cliente',
  'Impagos',
  'Documentación',
  'Nuevo préstamo Solicitud',
  'Reclamación',
  'LOPD',
  'Cambio de IBAN',
  'Cambios Datos personales',
  'Rescate solicitud DNI-Desarrollo Riesgo',
  'Rescate solicitud justificante IBAN-Desarrollo Riesgo',
  'Amazon',
  'Amazon desistimiento',
  'Desistimiento',
].map(i => ({value: i, text: i}));

export const outbound = [
  '',
  'Registro',
  'Amortización',
  'Desarrollo Riesgo',
  'Cuando recibiré mi dinero',
  'Impagos',
  'Documentación',
  'Nuevo préstamo Solicitud',
  'Reclamación',
  'LOPD',
  'Rescate solicitud DNI-Desarrollo Riesgo',
  'Rescate solicitud justificante IBAN-Desarrollo Riesgo',
  'Amazon',
  'Amazon desistimiento',
  'Desistimiento',
].map(i => ({value: i, text: i}));
