import {userRoles} from 'utils/user-permissions';

const {customerCare, finance, collections, it, admission, auditor} = userRoles;

/* ALL PERMISSION ITEMS
  customerCare.owner,
  customerCare.inAgent,
  customerCare.outAgent,
  customerCare.p3Agent,
  admission.owner,
  admission.analist,
  finance.owner,
  finance.accountant,
  finance.agent,
  collections.owner,
  collections.inAgent,
  collections.outAgent,
  it.owner,
  it.developer,
*/

export default {
  'customercare/amortizations': [
    customerCare.owner,
    customerCare.inAgent,
    customerCare.outAgent,
    admission.owner,
    admission.analist,
    collections.owner,
    collections.inAgent,
    it.owner,
  ],
  search: [
    customerCare.owner,
    customerCare.inAgent,
    customerCare.outAgent,
    customerCare.p3Agent,
    admission.owner,
    admission.analist,
    finance.owner,
    finance.accountant,
    finance.agent,
    collections.owner,
    collections.inAgent,
    collections.outAgent,
    it.owner,
    auditor.main,
  ],
  'customercare/paymentapplication': [
    collections.owner,
    collections.inAgent,
    finance.owner,
    it.owner,
  ],
  'p3/import': [
    admission.owner,
    admission.analist,
    collections.owner,
    customerCare.p3Agent,
    it.owner,
  ],
  'client/:clientId': [
    customerCare.owner,
    customerCare.inAgent,
    customerCare.outAgent,
    customerCare.p3Agent,
    admission.owner,
    admission.analist,
    finance.owner,
    finance.accountant,
    finance.agent,
    collections.owner,
    collections.inAgent,
    collections.outAgent,
    it.owner,
    auditor.main,
  ],
  'finance/operations/conciliation': [
    finance.owner,
    finance.agent,
    collections.owner,
    it.owner,
  ],
  'finance/operations/lots': [
    admission.owner,
    admission.analist,
    finance.owner,
    finance.agent,
    collections.owner,
    it.owner,
    auditor.main,
  ],
  'finance/operations/remittances': [
    finance.owner,
    finance.agent,
    collections.owner,
    collections.inAgent,
    collections.outAgent,
    it.owner,
    it.developer,
    auditor.main,
  ],
  'finance/operations/receipts': [
    customerCare.owner,
    customerCare.inAgent,
    customerCare.outAgent,
    collections.inAgent,
    admission.owner,
    finance.owner,
    finance.agent,
    finance.accountant,
    collections.owner,
    it.owner,
  ],
  'finance/accounting/erp': [finance.owner, finance.accountant, it.owner],
  'finance/receipt/:receiptId': [
    customerCare.owner,
    customerCare.inAgent,
    customerCare.outAgent,
    collections.inAgent,
    finance.owner,
    finance.agent,
    finance.accountant,
    collections.owner,
    it.owner,
  ],
  'collections/calendar': [collections.owner, collections.inAgent, it.owner],
  'collections/wallet': [
    finance.owner,
    finance.agent,
    collections.owner,
    collections.inAgent,
    it.owner,
  ],
  'collections/refinance': [
    admission.owner,
    admission.analist,
    collections.owner,
    collections.inAgent,
    collections.outAgent,
    it.owner,
  ],
  'collections/judicial': [
    finance.owner,
    finance.agent,
    collections.owner,
    collections.inAgent,
    collections.outAgent,
    it.owner,
  ],
  'customercare/reunifications': [
    customerCare.owner,
    admission.owner,
    admission.analist,
    finance.owner,
    collections.owner,
    it.owner,
  ],
  'customercare/reunification/:reunificationId': [
    customerCare.owner,
    admission.owner,
    admission.analist,
    finance.owner,
    collections.owner,
    it.owner,
  ],
  'collections/mailing': [collections.owner, it.owner],
  'collections/returns': [collections.owner, it.owner],
  'customercare/reloads': [
    customerCare.owner,
    customerCare.inAgent,
    customerCare.outAgent,
    customerCare.p3Agent,
    admission.owner,
    admission.analist,
    finance.owner,
    finance.accountant,
    finance.agent,
    collections.owner,
    collections.inAgent,
    collections.outAgent,
    it.owner,
    it.developer,
  ],
  'settings/permissions': [
    customerCare.owner,
    customerCare.inAgent,
    customerCare.outAgent,
    customerCare.p3Agent,
    admission.owner,
    admission.analist,
    finance.owner,
    finance.accountant,
    finance.agent,
    collections.owner,
    collections.inAgent,
    collections.outAgent,
    it.owner,
    it.developer,
    auditor.main,
    '',
  ],
  'permissions/management': [it.owner],
  'settings/user/management': [it.owner],
  'customercare/templates': [
    customerCare.owner,
    it.owner,
    collections.owner,
  ],
};
